"""empty message

Revision ID: 3e958d2d45c8
Revises: None
Create Date: 2016-04-30 08:43:12.018906

"""

# revision identifiers, used by Alembic.
revision = '3e958d2d45c8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('myprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_myprofile_email'), 'myprofile', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_myprofile_email'), table_name='myprofile')
    op.drop_table('myprofile')
    ### end Alembic commands ###
